# Generated by Django 3.1.5 on 2021-01-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='Product-Table',
        ),
    ]
