# Generated by Django 3.1.5 on 2021-01-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210112_1357'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='product_table',
        ),
    ]
